server:
  port: 9314
spring:
  datasource:
    #url: jdbc:postgresql://localhost:5433/medical_db
    url: jdbc:postgresql://localhost:5433/house_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update # Временно используем update для синхронизации схемы
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  insurance:
    timeout: 5000